sort CommRs by sector id + add JSON marshal/unmarshal methods
filecoin-project/go-sectorbuilder pull request #27
Opened 2019-09-20 20:46 UTC by laser

Fixes #23 

## Why does this PR exist?

PoSt generation and verification require their input CommRs be provided in the same order. @whyrusleeping pointed out that we're sorting on replica-bytes and we could be sorting by sector id instead.

## What's in this PR?

This PR updates the sorter to use sector id instead of bytes, and adds a JSON marshal/unmarshal method pair as per @anorth.

2019-09-20 22:13 UTC, dignifiedquire requested changes
It makes little sense to change this, unless you also change the ordering in rust-fil-proofs: https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/post.rs#L35-L45

2019-09-21 01:58 UTC, whyrusleeping commented
@dignifiedquire part of my request was that I already have the sectors sorted by sector ID, no need to spend any more time sorting them by something else (especially since this will be happening inside the VM)

2019-09-21 23:02 UTC, laser commented
Sure, but that’s a different PR. This change can merge separately and will have no effect until the upstream change is made.

Do you wan the other change merged first?

On Fri, Sep 20, 2019, at 3:13 PM, Friedel Ziegelmayer wrote:
> *@dignifiedquire* requested changes on this pull request.
> 
> It makes little sense to change this, unless you also change the ordering in rust-fil-proofs: https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/api/post.rs#L35-L45
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/filecoin-project/go-sectorbuilder/pull/27?email_source=notifications&email_token=AAGX6G7GJT6VE7WX4VSY37DQKVDI3A5CNFSM4IY3ETA2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFPK4KY#pullrequestreview-291417643>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAGX6G5S6KK623EDUMQKI7LQKVDI3ANCNFSM4IY3ETAQ>.
>

2019-11-19 23:08 UTC, laser commented
This PR has been stale for several weeks; closing.

2019-11-19 23:08 UTC, closed without merging